# config/settings.yaml

# -----------------------
# General Settings
# -----------------------
random_seed: 42
device: "cuda"  # or "cpu"

# -----------------------
# Data Settings
# -----------------------
data:
  train_path: "data/preprocessed/client_0.csv"
  test_path: "data/preprocessed/client_1.csv"
  batch_size: 1
  graph_edge_columns: ["card1", "addr1"]

# -----------------------
# Model Settings
# -----------------------
model:
  type: "GCN"
  input_dim: null   # 자동 추정됨
  hidden_dim: 64
  output_dim: 2
  dropout: 0.5

# -----------------------
# Training Settings
# -----------------------
train:
  epochs: 5
  learning_rate: 0.001

# -----------------------
# Federated Learning Settings
# -----------------------
federated:
  rounds: 3
  server_address: "127.0.0.1:8080"
  clients: 
    - id: 0
      data_path: "data/preprocessed/client_0.csv"
    - id: 1
      data_path: "data/preprocessed/client_1.csv"

# -----------------------
# Evaluation Settings
# -----------------------
evaluate:
  metrics: ["accuracy", "precision", "recall", "f1"]
